# Site settings
title: Kubernetes musings by chrislovecnm
description: "Kubernetes musings by Chris Love - aka chrislovecnm"
url: "https://k8spro.com"
author:
  name: "Chris Love"
  email: "blog@cnmconsulting.net"
  url: "https://k8spro.com"

# Build settings
baseurl: 
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

exclude: [vendor]

twitter_username:     chrislovecnm
github_username:      chrislovecnm
